version: "2.4"

services:
  aida:
    image: httpd  
    build: .
    ports:
      - "80:80"
    command: apache2ctl -D FOREGROUND
    volumes:
      -  <your AIDA Code local folder>:/var/www/html/aida
    links: 
            - "db:mysql-aida"
    environment:
      UPLOAD_LIMIT: 10G            
    cpus: 4
  db:
    image: mysql:8.0.31
    hostname: mysql-aida
    command: --default-authentication-plugin=mysql_native_password --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_connections=1000
    security_opt:
      - seccomp:unconfined
    environment:
      -  MYSQL_ALLOW_EMPTY_PASSWORD=1
      #-  MYSQL_RANDOM_ROOT_PASSWORD=1        
    restart: always
    volumes:
      -  <your AIDA DB local folder>:/var/lib/mysql
    ports:
      - "3306:3306" 
    cpus: 1
    
  dbfake:
    image: mysql:8.0.31
    hostname: aida-fake
    command: --default-authentication-plugin=mysql_native_password --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION --max_connections=1000
    security_opt:
      - seccomp:unconfined
    environment:
      -  MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      -  <your Fake Data DB local folder>:/var/lib/mysql
    ports:
      - "3307:3306" 
    expose:
      - 3307
    cpus: 1    
    
  phpmyadmin_fake:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: aida-fake
      PMA_USER: lota
      PMA_PASSWORD: VerdiLoTA2024!
    ports:
      - "8080:80"

  phpmyadmin_app:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-aida
    ports:
      - "8082:80"
   